# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CommunicationSetting.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1481, 990)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border-color: rgb(170, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.groupBox)
        self.frame_3.setStyleSheet("QFrame{\n"
"border:1px solid rgb(255, 255, 255)\n"
"} ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_edge_noise_reduction_threshold = QtWidgets.QLabel(self.frame_3)
        self.label_edge_noise_reduction_threshold.setObjectName("label_edge_noise_reduction_threshold")
        self.gridLayout_2.addWidget(self.label_edge_noise_reduction_threshold, 15, 0, 1, 1)
        self.label_gamma_2d = QtWidgets.QLabel(self.frame_3)
        self.label_gamma_2d.setObjectName("label_gamma_2d")
        self.gridLayout_2.addWidget(self.label_gamma_2d, 12, 0, 1, 1)
        self.label_use_projector_capturing_2d_image = QtWidgets.QLabel(self.frame_3)
        self.label_use_projector_capturing_2d_image.setObjectName("label_use_projector_capturing_2d_image")
        self.gridLayout_2.addWidget(self.label_use_projector_capturing_2d_image, 19, 0, 1, 1)
        self.label_projector_color = QtWidgets.QLabel(self.frame_3)
        self.label_projector_color.setObjectName("label_projector_color")
        self.gridLayout_2.addWidget(self.label_projector_color, 17, 0, 1, 1)
        self.label_gamma_3d = QtWidgets.QLabel(self.frame_3)
        self.label_gamma_3d.setObjectName("label_gamma_3d")
        self.gridLayout_2.addWidget(self.label_gamma_3d, 13, 0, 1, 1)
        self.label__exposure_time_2d = QtWidgets.QLabel(self.frame_3)
        self.label__exposure_time_2d.setObjectName("label__exposure_time_2d")
        self.gridLayout_2.addWidget(self.label__exposure_time_2d, 8, 0, 1, 1)
        self.label_gain_3d = QtWidgets.QLabel(self.frame_3)
        self.label_gain_3d.setObjectName("label_gain_3d")
        self.gridLayout_2.addWidget(self.label_gain_3d, 11, 0, 1, 1)
        self.label_gain_2d = QtWidgets.QLabel(self.frame_3)
        self.label_gain_2d.setObjectName("label_gain_2d")
        self.gridLayout_2.addWidget(self.label_gain_2d, 10, 0, 1, 1)
        self.label_light_contrast_threshold = QtWidgets.QLabel(self.frame_3)
        self.label_light_contrast_threshold.setObjectName("label_light_contrast_threshold")
        self.gridLayout_2.addWidget(self.label_light_contrast_threshold, 14, 0, 1, 1)
        self.label__exposure_time_3d = QtWidgets.QLabel(self.frame_3)
        self.label__exposure_time_3d.setObjectName("label__exposure_time_3d")
        self.gridLayout_2.addWidget(self.label__exposure_time_3d, 9, 0, 1, 1)
        self.label_transform_to_camera = QtWidgets.QLabel(self.frame_3)
        self.label_transform_to_camera.setObjectName("label_transform_to_camera")
        self.gridLayout_2.addWidget(self.label_transform_to_camera, 18, 0, 1, 1)
        self.comboBox_projector_color = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_projector_color.setObjectName("comboBox_projector_color")
        self.comboBox_projector_color.addItem("")
        self.comboBox_projector_color.addItem("")
        self.comboBox_projector_color.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_projector_color, 17, 1, 1, 1)
        self.horizontalSlider_projector_brightness = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_projector_brightness.setMaximum(240)
        self.horizontalSlider_projector_brightness.setProperty("value", 240)
        self.horizontalSlider_projector_brightness.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_projector_brightness.setObjectName("horizontalSlider_projector_brightness")
        self.gridLayout_2.addWidget(self.horizontalSlider_projector_brightness, 16, 1, 1, 1)
        self.comboBox_transform_to_camera = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_transform_to_camera.setObjectName("comboBox_transform_to_camera")
        self.comboBox_transform_to_camera.addItem("")
        self.comboBox_transform_to_camera.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_transform_to_camera, 18, 1, 1, 1)
        self.comboBox_use_projector_capturing_2d_image = QtWidgets.QComboBox(self.frame_3)
        self.comboBox_use_projector_capturing_2d_image.setObjectName("comboBox_use_projector_capturing_2d_image")
        self.comboBox_use_projector_capturing_2d_image.addItem("")
        self.comboBox_use_projector_capturing_2d_image.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_use_projector_capturing_2d_image, 19, 1, 1, 1)
        self.label_camera_state = QtWidgets.QLabel(self.frame_3)
        self.label_camera_state.setObjectName("label_camera_state")
        self.gridLayout_2.addWidget(self.label_camera_state, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalSlider_gain_3d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_gain_3d.setMaximum(10)
        self.horizontalSlider_gain_3d.setPageStep(1)
        self.horizontalSlider_gain_3d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_gain_3d.setObjectName("horizontalSlider_gain_3d")
        self.gridLayout_2.addWidget(self.horizontalSlider_gain_3d, 11, 1, 1, 1)
        self.horizontalSlider_gain_2d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_gain_2d.setMaximum(10)
        self.horizontalSlider_gain_2d.setPageStep(1)
        self.horizontalSlider_gain_2d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_gain_2d.setObjectName("horizontalSlider_gain_2d")
        self.gridLayout_2.addWidget(self.horizontalSlider_gain_2d, 10, 1, 1, 1)
        self.horizontalSlider_exposure_time_2d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_exposure_time_2d.setMinimum(3)
        self.horizontalSlider_exposure_time_2d.setMaximum(100)
        self.horizontalSlider_exposure_time_2d.setPageStep(1)
        self.horizontalSlider_exposure_time_2d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_exposure_time_2d.setObjectName("horizontalSlider_exposure_time_2d")
        self.gridLayout_2.addWidget(self.horizontalSlider_exposure_time_2d, 8, 1, 1, 1)
        self.horizontalSlider_exposure_time_3d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_exposure_time_3d.setMinimum(3)
        self.horizontalSlider_exposure_time_3d.setMaximum(100)
        self.horizontalSlider_exposure_time_3d.setPageStep(1)
        self.horizontalSlider_exposure_time_3d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_exposure_time_3d.setObjectName("horizontalSlider_exposure_time_3d")
        self.gridLayout_2.addWidget(self.horizontalSlider_exposure_time_3d, 9, 1, 1, 1)
        self.horizontalSlider_gamma_2d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_gamma_2d.setMaximum(10)
        self.horizontalSlider_gamma_2d.setPageStep(1)
        self.horizontalSlider_gamma_2d.setProperty("value", 1)
        self.horizontalSlider_gamma_2d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_gamma_2d.setObjectName("horizontalSlider_gamma_2d")
        self.gridLayout_2.addWidget(self.horizontalSlider_gamma_2d, 12, 1, 1, 1)
        self.horizontalSlider_gamma_3d = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_gamma_3d.setMaximum(10)
        self.horizontalSlider_gamma_3d.setProperty("value", 1)
        self.horizontalSlider_gamma_3d.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_gamma_3d.setObjectName("horizontalSlider_gamma_3d")
        self.gridLayout_2.addWidget(self.horizontalSlider_gamma_3d, 13, 1, 1, 1)
        self.horizontalSlider_light_contrast_threshold = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_light_contrast_threshold.setMaximum(10)
        self.horizontalSlider_light_contrast_threshold.setProperty("value", 1)
        self.horizontalSlider_light_contrast_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_light_contrast_threshold.setObjectName("horizontalSlider_light_contrast_threshold")
        self.gridLayout_2.addWidget(self.horizontalSlider_light_contrast_threshold, 14, 1, 1, 1)
        self.horizontalSlider_edge_noise_reduction_threshold = QtWidgets.QSlider(self.frame_3)
        self.horizontalSlider_edge_noise_reduction_threshold.setMaximum(10)
        self.horizontalSlider_edge_noise_reduction_threshold.setProperty("value", 1)
        self.horizontalSlider_edge_noise_reduction_threshold.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_edge_noise_reduction_threshold.setObjectName("horizontalSlider_edge_noise_reduction_threshold")
        self.gridLayout_2.addWidget(self.horizontalSlider_edge_noise_reduction_threshold, 15, 1, 1, 1)
        self.label_projector_brightness = QtWidgets.QLabel(self.frame_3)
        self.label_projector_brightness.setObjectName("label_projector_brightness")
        self.gridLayout_2.addWidget(self.label_projector_brightness, 16, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_connect = QtWidgets.QPushButton(self.frame)
        self.pushButton_connect.setObjectName("pushButton_connect")
        self.verticalLayout.addWidget(self.pushButton_connect)
        self.pushButton_disconnect = QtWidgets.QPushButton(self.frame)
        self.pushButton_disconnect.setObjectName("pushButton_disconnect")
        self.verticalLayout.addWidget(self.pushButton_disconnect)
        self.pushButton_capture = QtWidgets.QPushButton(self.frame)
        self.pushButton_capture.setObjectName("pushButton_capture")
        self.verticalLayout.addWidget(self.pushButton_capture)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "相机参数设置"))
        self.label_edge_noise_reduction_threshold.setText(_translate("MainWindow", "边缘去噪:"))
        self.label_gamma_2d.setText(_translate("MainWindow", "2D相机gamma:"))
        self.label_use_projector_capturing_2d_image.setText(_translate("MainWindow", "2D相机是否使用光机"))
        self.label_projector_color.setText(_translate("MainWindow", "投影颜色"))
        self.label_gamma_3d.setText(_translate("MainWindow", "3D相机gamma:"))
        self.label__exposure_time_2d.setText(_translate("MainWindow", "2D曝光时间:"))
        self.label_gain_3d.setText(_translate("MainWindow", "3D相机增益:"))
        self.label_gain_2d.setText(_translate("MainWindow", "2D相机增益:"))
        self.label_light_contrast_threshold.setText(_translate("MainWindow", "光强对比度阈值:"))
        self.label__exposure_time_3d.setText(_translate("MainWindow", "3D曝光时间:"))
        self.label_transform_to_camera.setText(_translate("MainWindow", "坐标系选择"))
        self.comboBox_projector_color.setItemText(0, _translate("MainWindow", "blue"))
        self.comboBox_projector_color.setItemText(1, _translate("MainWindow", "red"))
        self.comboBox_projector_color.setItemText(2, _translate("MainWindow", "green"))
        self.comboBox_transform_to_camera.setItemText(0, _translate("MainWindow", "左相机坐标系"))
        self.comboBox_transform_to_camera.setItemText(1, _translate("MainWindow", "右相机坐标系"))
        self.comboBox_use_projector_capturing_2d_image.setItemText(0, _translate("MainWindow", "是"))
        self.comboBox_use_projector_capturing_2d_image.setItemText(1, _translate("MainWindow", "否"))
        self.label_camera_state.setText(_translate("MainWindow", "断开"))
        self.label.setText(_translate("MainWindow", "相机状态："))
        self.label_projector_brightness.setText(_translate("MainWindow", "投影亮度:"))
        self.pushButton.setText(_translate("MainWindow", "修改"))
        self.pushButton_connect.setText(_translate("MainWindow", "连接相机"))
        self.pushButton_disconnect.setText(_translate("MainWindow", "断开相机"))
        self.pushButton_capture.setText(_translate("MainWindow", "拍摄"))
