# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionTest.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1481, 1022)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("border-color: rgb(170, 170, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame{\n"
"border:1px solid rgb(77, 125, 253)\n"
"} ")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBox)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.horizontalLayout.addWidget(self.tableWidget)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.horizontalLayout_2.addWidget(self.frame_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_add_pos = QtWidgets.QPushButton(self.frame)
        self.pushButton_add_pos.setObjectName("pushButton_add_pos")
        self.verticalLayout_4.addWidget(self.pushButton_add_pos)
        self.pushButton_del_pos = QtWidgets.QPushButton(self.frame)
        self.pushButton_del_pos.setObjectName("pushButton_del_pos")
        self.verticalLayout_4.addWidget(self.pushButton_del_pos)
        self.pushButton_save = QtWidgets.QPushButton(self.frame)
        self.pushButton_save.setObjectName("pushButton_save")
        self.verticalLayout_4.addWidget(self.pushButton_save)
        self.pushButton_start_get_points = QtWidgets.QPushButton(self.frame)
        self.pushButton_start_get_points.setObjectName("pushButton_start_get_points")
        self.verticalLayout_4.addWidget(self.pushButton_start_get_points)
        self.pushButton_stop_get_points = QtWidgets.QPushButton(self.frame)
        self.pushButton_stop_get_points.setObjectName("pushButton_stop_get_points")
        self.verticalLayout_4.addWidget(self.pushButton_stop_get_points)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_coor = QtWidgets.QLabel(self.groupBox_2)
        self.label_coor.setObjectName("label_coor")
        self.gridLayout_2.addWidget(self.label_coor, 1, 1, 1, 1)
        self.label_c = QtWidgets.QLabel(self.groupBox_2)
        self.label_c.setObjectName("label_c")
        self.gridLayout_2.addWidget(self.label_c, 7, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 7, 0, 1, 1)
        self.label_x = QtWidgets.QLabel(self.groupBox_2)
        self.label_x.setObjectName("label_x")
        self.gridLayout_2.addWidget(self.label_x, 2, 1, 1, 1)
        self.label_a = QtWidgets.QLabel(self.groupBox_2)
        self.label_a.setObjectName("label_a")
        self.gridLayout_2.addWidget(self.label_a, 5, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 6, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_b = QtWidgets.QLabel(self.groupBox_2)
        self.label_b.setObjectName("label_b")
        self.gridLayout_2.addWidget(self.label_b, 6, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.label_z = QtWidgets.QLabel(self.groupBox_2)
        self.label_z.setObjectName("label_z")
        self.gridLayout_2.addWidget(self.label_z, 4, 1, 1, 1)
        self.label_y = QtWidgets.QLabel(self.groupBox_2)
        self.label_y.setObjectName("label_y")
        self.gridLayout_2.addWidget(self.label_y, 3, 1, 1, 1)
        self.label_time = QtWidgets.QLabel(self.groupBox_2)
        self.label_time.setText("")
        self.label_time.setObjectName("label_time")
        self.gridLayout_2.addWidget(self.label_time, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_2.setStretch(0, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "拍摄位置"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Z"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "A"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "B"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "C"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "坐标系"))
        self.pushButton_add_pos.setText(_translate("MainWindow", "添加位置"))
        self.pushButton_del_pos.setText(_translate("MainWindow", "删除位置"))
        self.pushButton_save.setText(_translate("MainWindow", "保存位置"))
        self.pushButton_start_get_points.setText(_translate("MainWindow", "开启监控"))
        self.pushButton_stop_get_points.setText(_translate("MainWindow", "关闭监控"))
        self.groupBox_2.setTitle(_translate("MainWindow", "当前位置"))
        self.label_coor.setText(_translate("MainWindow", "关节"))
        self.label_c.setText(_translate("MainWindow", "0"))
        self.label_7.setText(_translate("MainWindow", "坐标系："))
        self.label_6.setText(_translate("MainWindow", "C:"))
        self.label_x.setText(_translate("MainWindow", "0"))
        self.label_a.setText(_translate("MainWindow", "0"))
        self.label_2.setText(_translate("MainWindow", "Y:"))
        self.label_3.setText(_translate("MainWindow", "Z:"))
        self.label_5.setText(_translate("MainWindow", "B:"))
        self.label_4.setText(_translate("MainWindow", "A:"))
        self.label_b.setText(_translate("MainWindow", "0"))
        self.label.setText(_translate("MainWindow", "X:"))
        self.label_z.setText(_translate("MainWindow", "0"))
        self.label_y.setText(_translate("MainWindow", "0"))
